config/routes.rb
Instanthub::Application.routes.draw do
  resources :searches
  match "/perma/:link", :to => "searches#show", :as => :permalink
  match "/search", :to => "searches#new"
  root :to => "searches#new"
end

app/models/search.rb
class Search < ActiveRecord::Base
  after_create :assign_permalink

  private
  def assign_permalink
    update_attribute(:permalink, id.to_s(36))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
    @original_terms = params[:q]

    query = params[:q]
    terms, @options = prepare_terms_and_options(query)
    @repositories = Github.repositories(terms, @options) if query
  end

  def show
    @search = Search.find_by_permalink(params[:link])
    if @search
      @original_terms = @search.q

      query = @search.q
      terms, @options = prepare_terms_and_options(query)
      @repositories = Github.repositories(terms, @options) if query
      render :template => "searches/new"
    else
      redirect_to '/'
    end
  end

  def create
    @search = Search.create!(:q => params[:q])
    redirect_to "/perma/#{@search.permalink}"
  end

  protected
  def prepare_terms_and_options(terms, options = {})
    parameters = {
      :watchers => /w:(\d+)/i,
      :forks => /f:(\d+)/i,
      :pushed_at => /p:(\d+)/i,
      :sort => /s:(\w+)/i,
      :language => /l:(\w+)/i,
      :force => /(--force)/i
    }

    parameters.each do |k,v|
      if v.match(terms)
        options[k] = v.match(terms)[1]
        terms = terms.gsub(v, '')
      end
    end

    if options
      options.delete(:sort) unless %w(pushed_at score watchers forks).include? options[:sort]
      options.delete(:language) unless Github::LANGUAGES.keys.include? options[:language]
    end
    [terms, options]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Hubscovery
    = stylesheet_link_tag :all
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Droid+Sans'
    = javascript_include_tag :defaults
    = csrf_meta_tag
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23300472-1']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();
    %body
      .row
        .column.grid_12
          %h1
            =link_to 'Hubscovery', '/'
      .row
        .column.grid_8
          = yield
        .column.grid_4
          = yield(:sidebar)
        .row
          .column.grid_12
            %p
              built by
              %a{:href => "mailto:jschoolcraft@aissaclabs.com"} Jeff Schoolcraft
              at
              = succeed "," do
                %a{:href => "http://thequeue.net"} The Queue Incorporated
              \&copy; #{Date.today.year}

app/views/searches/_sidebar.html.haml
%h4 Options
%ul
  %li w:# (watchers:minimum) ex. w:6 => has 6 or more watchers
  %li f:# (forks:minimum) ex. f:2 => has 2 or more forks
  %li p:# (pushed_at:within_weeks.ago) ex. p:4 => was pushed to within 4 weeks
  %li s:choice (sorted by "choice") ex. s:pushed_at => sort by "pushed_at" choices (pushed_at, score, watchers, forks)
  %li l:language (language:language) ex. l:ruby => language is ruby (more below)
  %li --force (because every command worth running has this option)
%h4 Defaults
%pre
  w:6 f:2 p:26 s:score
%ul
  %li minimum of 6 watchers and 2 forks
  %li pushed to in last 26 weeks (6 months)
  %li sorted by "score" (think lucene/sphinx/etc)

%h4 Languages
%p All "popular" languages from Github are supported, including:
%ul
  - Github::LANGUAGES.each do |k,v|
    %li= "#{k} - #{v}"

app/views/searches/new.html.haml
%form{:action => "/search"}
  %label{:for => "q"}
    github repository search
    %input{:name => "q", :value => @original_terms }
#results
  - if @repositories
    #permalink
      - if @search && @search.permalink
        permalink:
        = link_to permalink_url(@search.permalink)
      - else
        = link_to 'create permalink', searches_path(:q => @original_terms), :method => :post, :action => :create
    - @repositories.each do |repo|
      %div
        .name
          %a{ :href => repo["url"] }
            = repo["name"]
      .author
        by:
        %a{ :href => "https://github.com/#{repo["owner"]}" }
          = repo["owner"]
      - unless repo["homepage"].blank?
        .urls
          %a{ :href => repo["homepage"] } Home Page
      .description= repo["description"]
      .details
        %p
          Language:
          = repo["language"]
          | Last updated:
          = Date.parse(repo["pushed_at"]).to_s
          | Watchers:
          = repo["watchers"]
          | Forks:
          = repo["forks"]
  - else
    %p Search for something, like rspec
    %p Hints:
    %ul
      %li doesn't work for user names
      %li doesn't work without trying to find a repo (no bare w:3 type searches)

    %h3 Discovery
    %p If you're trying to find something and you're not quite sure what it is you have a few options.
    %ul
      %li Search Rails and Search Ruby (curated Google custom search)
      %li Github's Native Explore (though admittedly you need a pretty good idea of what you want)
      %li Ruby Toolbox
  %br

- content_for :sidebar do
  = render :partial => "sidebar"